FROM ubuntu:latest
MAINTAINER rahulkotla91@yahoo.com

RUN apt-get update
RUN apt-get install -y build-essential
RUN apt-get install -y cmake
RUN apt-get install -y libevent-dev
RUN apt-get install -y redis-server


